### ISSUE TITLE
Error: Too many positional arguments: 0 allowed, but 6 found.

### ISSUE THREAD

**Issue by Yoda-Man** [NehilKoshiya/uni_payments#1]
Building with sound null safety 

/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/uni_payments-0.0.2/lib/methods/paytm_service.dart:47:47: Error: Too many positional arguments: 0 allowed, but 6 found.
Try removing the extra positional arguments.
        var paytmResponse = Paytm.payWithPaytm(paytmMerchantId, orderId,
                                              ^
/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/paytm-3.0.1/lib/paytm.dart:9:40: Context: Found this candidate, but the arguments don't match.
  static Future<Map<dynamic, dynamic>> payWithPaytm({
                                       ^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan  to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 8s
Running Gradle task 'bundleRelease'...                            130,3s
Gradle task bundleRelease failed with exit code 1

**Comment by NehilKoshiya** [comment]
> Building with sound null safety
> 
> /C:/Flutter/.pub-cache/hosted/pub.dartlang.org/uni_payments-0.0.2/lib/methods/paytm_service.dart:47:47: Error: Too many positional arguments: 0 allowed, but 6 found. Try removing the extra positional arguments. var paytmResponse = Paytm.payWithPaytm(paytmMerchantId, orderId, ^ /C:/Flutter/.pub-cache/hosted/pub.dartlang.org/paytm-3.0.1/lib/paytm.dart:9:40: Context: Found this candidate, but the arguments don't match. static Future<Map<dynamic, dynamic>> payWithPaytm({ ^^^^^^^^^^^^
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'C:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildRelease'.
> 
> > Process 'command 'C:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan  to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 8s Running Gradle task 'bundleRelease'... 130,3s Gradle task bundleRelease failed with exit code 1

you have to pass the appropriate argument as per required data in the Paytm method.

**Comment by Yoda-Man** [comment]
I only get the error when I try build the appbundle it was working fine when I ran it on the emulator

**Comment by Yoda-Man** [comment]
I was using the paystack option

**Comment by Tushar8Sharma** [comment]
I am also facing same issue.
While I am using razorpay option I am getting this paytm issue.

**Comment by antruongnguyen** [comment]
The issue is caused by `paytm` version `3.0.1`. In this project, the version of `paytm` is locked to `3.0.0`.

There are 2 ways to fix this issue:

1. Stick with `paytm` version `3.0.0`
2. With `paytm` version `3.0.1`, modify [lib/methods/paytm_service.dart (line: 47-48)](https://github.com/NehilKoshiya/uni_payments/blob/a2b86bdc7cf80d719e817f10be5776faa900db7b/lib/methods/paytm_service.dart#L47) to `Paytm.payWithPaytm(mId: paytmMerchantId, orderId: orderId, txnToken: txnToken, txnAmount: amount.toString(), callBackUrl: callBackUrl, staging: isTesting);`

🍻
